#!/usr/bin/perl
use strict;
use warnings;

use feature ':5.10';

use PicBot; # frijole made me do it

given ($ARGV[0]) {
    when ('freenode') {
        PicBot::spawn('picbot', 'irc.freenode.net',
                      '##turtles', '#peltkore');
    }
    when ('slashnet') {
        PicBot::spawn('ikki', 'irc.slashnet.org', '#mefi');
    }
    when ('testnet') {
        PicBot::spawn('picbot', 'irc.freenode.net:9001', '##turtles');
    }

    default { print STDERR "$0 <network>\n"; exit 1 }
}
